apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app
  namespace: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: java-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: java-app-pod      
      labels:
        app: java-app
    spec:
      containers:
      - name: java-appc       
        image: ijehifeanyi/app
        ports:
        - containerPort: 8080 

---
apiVersion: v1
kind: Service
metadata:
  name: my-java-app
  namespace: test
spec:
  selector:
    app: java-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort